"""
定时任务常量定义

集中管理调度器、触发器、告警等模块的硬编码阈值，
便于统一调整与维护。
"""

# 默认任务配置
DEFAULT_MAX_INSTANCES = 1
"""默认最大并发实例数"""
DEFAULT_MISFIRE_GRACE_TIME = 3600
"""默认错过执行的宽限时间(秒)"""
DEFAULT_PRIORITY = 10
"""默认任务优先级"""

# 告警默认阈值
DEFAULT_ALERT_FAILURE_RATE_THRESHOLD = 0.3
"""默认失败率阈值(0-1)"""
DEFAULT_ALERT_CONSECUTIVE_FAILURES = 5
"""默认连续失败阈值"""
DEFAULT_ALERT_TIMEOUT_THRESHOLD = 300.0
"""默认超时阈值(秒)"""
DEFAULT_ALERT_LONG_RUNNING_THRESHOLD = 600.0
"""默认长时间运行阈值(秒)"""
DEFAULT_ALERT_QUEUE_THRESHOLD = 100
"""默认队列积压阈值"""
DEFAULT_ALERT_CHECK_INTERVAL = 60.0
"""默认告警检查间隔(秒)"""
DEFAULT_ALERT_COOLDOWN = 300.0
"""默认告警冷却时间(秒)"""
DEFAULT_ALERT_HISTORY_MAX = 1000
"""默认告警历史保留条数"""
DEFAULT_ALERT_MIN_TOTAL_EXECUTIONS = 10
"""默认失败率告警的最小执行次数门槛"""

# Cron 字段范围
CRON_YEAR_MIN = 1970
CRON_YEAR_MAX = 2099
CRON_MONTH_MIN = 1
CRON_MONTH_MAX = 12
CRON_DAY_MIN = 1
CRON_DAY_MAX = 31
CRON_HOUR_MIN = 0
CRON_HOUR_MAX = 23
CRON_MINUTE_MIN = 0
CRON_MINUTE_MAX = 59
CRON_SECOND_MIN = 0
CRON_SECOND_MAX = 59
CRON_DAY_OF_WEEK_MIN = 0
CRON_DAY_OF_WEEK_MAX = 6

# 调度器配置
SCHEDULER_MAX_CRON_ITERATIONS = 1000
"""Cron 触发器最大迭代次数"""
SCHEDULER_MAX_DAYS_CHECK = 366
"""Cron 触发器最大天数检查次数"""
SCHEDULER_SHUTDOWN_WAIT = 5.0
"""调度器关闭等待时间(秒)"""
SCHEDULER_EVENT_HISTORY_MAX = 1000
"""事件历史最大保留条数"""
SCHEDULER_EXECUTOR_SHUTDOWN_WAIT = 30.0
"""执行器关闭等待时间(秒)"""
SCHEDULER_DEPENDENCY_RETRY_DELAY = 1.0
"""依赖未满足时的重试延迟(秒)"""
SCHEDULER_RUN_NOW_PRIORITY = -1000
"""立即执行任务的优先级"""

# 已完成任务记录的保留时间(秒)
COMPLETED_TASK_TTL = 86400
"""已完成任务记录的 TTL(秒)"""
