"""
定时任务常量定义
"""

# 默认配置
DEFAULT_MAX_INSTANCES = 1
DEFAULT_MISFIRE_GRACE_TIME = 3600  # 1小时
DEFAULT_PRIORITY = 10
DEFAULT_TIMEOUT = None  # 不限制
DEFAULT_RETRY_MAX_ATTEMPTS = 0  # 不重试
DEFAULT_RETRY_DELAY = 1.0  # 1秒
DEFAULT_RETRY_EXPONENTIAL_BACKOFF = True

# 告警配置
DEFAULT_ALERT_FAILURE_RATE_THRESHOLD = 0.3  # 30%失败率
DEFAULT_ALERT_CONSECUTIVE_FAILURES = 5  # 连续5次失败
DEFAULT_ALERT_TIMEOUT_THRESHOLD = 300.0  # 5分钟超时
DEFAULT_ALERT_LONG_RUNNING_THRESHOLD = 600.0  # 10分钟
DEFAULT_ALERT_QUEUE_THRESHOLD = 100  # 队列积压100
DEFAULT_ALERT_CHECK_INTERVAL = 60.0  # 1分钟检查一次
DEFAULT_ALERT_COOLDOWN = 300.0  # 5分钟冷却

# Cron字段范围
CRON_YEAR_MIN = 1970
CRON_YEAR_MAX = 2099
CRON_MONTH_MIN = 1
CRON_MONTH_MAX = 12
CRON_DAY_MIN = 1
CRON_DAY_MAX = 31
CRON_HOUR_MIN = 0
CRON_HOUR_MAX = 23
CRON_MINUTE_MIN = 0
CRON_MINUTE_MAX = 59
CRON_SECOND_MIN = 0
CRON_SECOND_MAX = 59
CRON_DAY_OF_WEEK_MIN = 0
CRON_DAY_OF_WEEK_MAX = 6

# 调度器配置
SCHEDULER_MAX_YEAR_ITERATIONS = 5
SCHEDULER_MAX_CRON_ITERATIONS = 1000
SCHEDULER_MAX_DAYS_CHECK = 366
SCHEDULER_SHUTDOWN_WAIT = 5.0  # 5秒等待
SCHEDULER_EVENT_HISTORY_MAX = 1000

# 日志清理
LOG_RETENTION_DAYS = 30
MAX_LOGS_PER_TASK = 1000
