"""LLM相关配置项

包含对话模型、嵌入模型、轻量模型、思考模式与Token额度等配置。
"""

from liuying.configs.utils import RegisterConfig

from ._common import MODULE

__all__ = ["LLM_CONFIGS"]

LLM_CONFIGS: list[RegisterConfig] = [
    RegisterConfig(
        key="CHAT_PROVIDER",
        value=None,
        module=MODULE,
        help="对话模型供应商，None时用默认",
        default_value=None,
        type=str,
    ),
    RegisterConfig(
        key="CHAT_MODEL",
        value=None,
        module=MODULE,
        help="对话模型名，None时用provider默认",
        default_value=None,
        type=str,
    ),
    RegisterConfig(
        key="EMBEDDING_PROVIDER",
        value=None,
        module=MODULE,
        help="嵌入模型供应商",
        default_value=None,
        type=str,
    ),
    RegisterConfig(
        key="EMBEDDING_MODEL",
        value=None,
        module=MODULE,
        help="嵌入模型名",
        default_value=None,
        type=str,
    ),
    RegisterConfig(
        key="THINKING_MODE_ENABLED",
        value=False,
        module=MODULE,
        help="是否开启深度思考请求（开启时向模型请求思考链）",
        default_value=False,
        type=bool,
    ),
    # ===== Phase11: LLM模型管理 =====
    RegisterConfig(
        key="LITE_MODEL_ENABLED",
        value=False,
        module=MODULE,
        help="是否启用轻量模型",
        default_value=False,
        type=bool,
    ),
    RegisterConfig(
        key="LITE_MODEL_PROVIDER",
        value=None,
        module=MODULE,
        help="轻量模型供应商",
        default_value=None,
        type=str,
    ),
    RegisterConfig(
        key="LITE_MODEL_NAME",
        value=None,
        module=MODULE,
        help="轻量模型名",
        default_value=None,
        type=str,
    ),
    RegisterConfig(
        key="STRICT_MAIN_MODEL",
        value=False,
        module=MODULE,
        help="是否严格使用主模型不降级",
        default_value=False,
        type=bool,
    ),
    RegisterConfig(
        key="MONTHLY_TOKEN_QUOTA",
        value=0,
        module=MODULE,
        help="月度token额度（0=不限）",
        default_value=0,
        type=int,
    ),
    # ===== 用户对话 Token 额度 =====
    RegisterConfig(
        key="TOKEN_QUOTA_ENABLED",
        value=True,
        module=MODULE,
        help="是否启用用户对话token额度限制",
        default_value=True,
        type=bool,
    ),
    RegisterConfig(
        key="TOKEN_QUOTA_REMINDER_CD",
        value=300,
        module=MODULE,
        help="用户额度不足提醒冷却（秒），防止消息刷屏",
        default_value=300,
        type=int,
    ),
    RegisterConfig(
        key="TOKEN_QUOTA_MIN_THRESHOLD",
        value=1,
        module=MODULE,
        help="用户可用token最低阈值，剩余低于此值视为不足",
        default_value=1,
        type=int,
    ),
    # ===== Phase3: 模型按角色路由 =====
    RegisterConfig(
        key="MODEL_INTENT",
        value=None,
        module=MODULE,
        help="意图推断角色模型名（None时回退到CHAT_MODEL）",
        default_value=None,
        type=str,
    ),
    RegisterConfig(
        key="MODEL_INTENT_TEMPERATURE",
        value=0.1,
        module=MODULE,
        help="意图推断角色温度",
        default_value=0.1,
        type=float,
    ),
    RegisterConfig(
        key="MODEL_REVIEW",
        value=None,
        module=MODULE,
        help="响应审查角色模型名（None时回退到CHAT_MODEL）",
        default_value=None,
        type=str,
    ),
    RegisterConfig(
        key="MODEL_REVIEW_TEMPERATURE",
        value=0.1,
        module=MODULE,
        help="响应审查角色温度",
        default_value=0.1,
        type=float,
    ),
    RegisterConfig(
        key="MODEL_AGENT",
        value=None,
        module=MODULE,
        help="Agent工具调用角色模型名（None时回退到CHAT_MODEL）",
        default_value=None,
        type=str,
    ),
    RegisterConfig(
        key="MODEL_AGENT_TEMPERATURE",
        value=0.3,
        module=MODULE,
        help="Agent工具调用角色温度",
        default_value=0.3,
        type=float,
    ),
    RegisterConfig(
        key="MODEL_STICKER",
        value=None,
        module=MODULE,
        help="贴纸选择角色模型名（None时回退到CHAT_MODEL）",
        default_value=None,
        type=str,
    ),
    RegisterConfig(
        key="MODEL_STICKER_TEMPERATURE",
        value=0.4,
        module=MODULE,
        help="贴纸选择角色温度",
        default_value=0.4,
        type=float,
    ),
    RegisterConfig(
        key="MODEL_WARMUP",
        value=None,
        module=MODULE,
        help="预热任务角色模型名（None时回退到CHAT_MODEL）",
        default_value=None,
        type=str,
    ),
    RegisterConfig(
        key="MODEL_WARMUP_TEMPERATURE",
        value=0.7,
        module=MODULE,
        help="预热任务角色温度",
        default_value=0.7,
        type=float,
    ),
    # ===== Phase4: AI Provider多CLI路由 =====
    RegisterConfig(
        key="AI_CLI_ENABLED",
        value=False,
        module=MODULE,
        help="是否启用CLI路由降级（HTTP provider全部失败时尝试CLI工具）",
        default_value=False,
        type=bool,
    ),
    RegisterConfig(
        key="AI_CLI_ROUTES",
        value="",
        module=MODULE,
        help='CLI路由列表JSON（如[{"name":"gemini_cli","command":["gemini"],"use_stdin":true,"timeout":30,"priority":1}]）',
        default_value="",
        type=str,
    ),
]
"""LLM相关配置项列表"""
